### ISSUE TITLE
After the update to 1.23.0 no longer works on Wiiu

### ISSUE THREAD

**Issue by tailshine** [libretro/beetle-vb-libretro#50]
> After the update to 1.23.0 this core no longer works on Wiiu

@ruijtunes
Please try these two builds:
https://github.com/tailshine/beetle-vb-libretro/blob/wiiu/mednafen_vb_libretro.7z?raw=true
https://github.com/tailshine/beetle-vb-libretro/blob/wiiu/mednafen_vb_libretro2.7z?raw=true

**Comment by ruijtunes** [comment]
None of this builds worked.
In attach are the logs.

The last build I have is from 10/11/2019

**Comment by ruijtunes** [comment]
I tested again with this builds and noticed that the games are running and
the audio is correct but no video just a black screen.

>

**Comment by twinaphex** [comment]
@tailshine 

Let's fix these issues as soon as possible. This is very concerning.

Also, in the past I took great pains to ensure some of these cores can compile with MSVC2003/2005/2010, now with the current version (because it's mostly upstream code), all these platforms no longer compile.

So we cannot have mostly in-line with upstream code, alterations have to be made, and in the future when we do upgrades, we need to be far more careful with what we change, some of these changes are made for a deliberate reason.

**Comment by twinaphex** [comment]
@ruijtunes After it works, also let us know if the core is still fast enough. That should definitely be tested across the other platforms like Wii as well.

**Comment by tailshine** [comment]
I do not know how to fix any of these problems or have those older compilers. :(

Thankfully I didn't submit any PRs for this repo. I suggest reverting my other repo commits to be safe also.

**Comment by ruijtunes** [comment]
The Core is working fine now on Wiiu. I tested VB Wario Land with fast CPU and the frame rate is 50Hz as it should most of the time. With acuraccy CPU the framerate drops to around 46Hz.
